// <auto-generated />
using System;
using DMF_Services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace DMF_Services.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602090508_AddCreatedDateToCarDetail")]
    partial class AddCreatedDateToCarDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DMF_Services.DTOs.Cars.WishlistToggleResultDto", b =>
                {
                    b.Property<bool>("IsWishlisted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("WishlistToggleResultDto");
                });

            modelBuilder.Entity("DMF_Services.Models.CarBrandRaw", b =>
                {
                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CarBrandRaw");
                });

            modelBuilder.Entity("DMF_Services.Models.CarDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("ABS")
                        .HasColumnType("bit");

                    b.Property<bool?>("AdjustableStaring")
                        .HasColumnType("bit");

                    b.Property<bool?>("AirBag")
                        .HasColumnType("bit");

                    b.Property<string>("AirCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AlloyWheels")
                        .HasColumnType("bit");

                    b.Property<bool?>("AntiTheftSystem")
                        .HasColumnType("bit");

                    b.Property<bool?>("Aux")
                        .HasColumnType("bit");

                    b.Property<bool?>("BSD")
                        .HasColumnType("bit");

                    b.Property<bool?>("Bluetooth")
                        .HasColumnType("bit");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Point>("CarLocation")
                        .HasColumnType("geography");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("DealersID")
                        .HasColumnType("int");

                    b.Property<bool?>("EBD")
                        .HasColumnType("bit");

                    b.Property<int?>("EnginCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Fuel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HillHold")
                        .HasColumnType("bit");

                    b.Property<string>("InsuranceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAccidental")
                        .HasColumnType("bit");

                    b.Property<int?>("KMDriven")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("MusicSystem")
                        .HasColumnType("bit");

                    b.Property<int?>("NoOfOwner")
                        .HasColumnType("int");

                    b.Property<bool?>("PowerStaring")
                        .HasColumnType("bit");

                    b.Property<bool?>("PowerWindow")
                        .HasColumnType("bit");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("RegistrationNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ServiceHistory")
                        .HasColumnType("bit");

                    b.Property<string>("Transmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Varient")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarDetail", (string)null);
                });

            modelBuilder.Entity("DMF_Services.Models.CarFilterRaw", b =>
                {
                    b.Property<bool?>("ABS")
                        .HasColumnType("bit");

                    b.Property<bool?>("AdjustableStaring")
                        .HasColumnType("bit");

                    b.Property<bool?>("AirBag")
                        .HasColumnType("bit");

                    b.Property<string>("AirCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AlloyWheels")
                        .HasColumnType("bit");

                    b.Property<bool?>("AntiTheftSystem")
                        .HasColumnType("bit");

                    b.Property<bool?>("Aux")
                        .HasColumnType("bit");

                    b.Property<bool?>("BSD")
                        .HasColumnType("bit");

                    b.Property<bool?>("Bluetooth")
                        .HasColumnType("bit");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("CarLat")
                        .HasColumnType("float");

                    b.Property<double?>("CarLon")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DealersID")
                        .HasColumnType("int");

                    b.Property<double?>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<bool?>("EBD")
                        .HasColumnType("bit");

                    b.Property<int?>("EnginCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Fuel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HillHold")
                        .HasColumnType("bit");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsuranceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAccidental")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWishlisted")
                        .HasColumnType("bit");

                    b.Property<int?>("KMDriven")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("MusicSystem")
                        .HasColumnType("bit");

                    b.Property<int?>("NoOfOwner")
                        .HasColumnType("int");

                    b.Property<bool?>("PowerStaring")
                        .HasColumnType("bit");

                    b.Property<bool?>("PowerWindow")
                        .HasColumnType("bit");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ServiceHistory")
                        .HasColumnType("bit");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Varient")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CarFilterRaw");
                });

            modelBuilder.Entity("DMF_Services.Models.CarImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarDetailID")
                        .HasColumnType("int");

                    b.Property<string>("Image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image9")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarDetailID")
                        .IsUnique();

                    b.ToTable("CarImage", (string)null);
                });

            modelBuilder.Entity("DMF_Services.Models.CarModelRaw", b =>
                {
                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CarModelRaw");
                });

            modelBuilder.Entity("DMF_Services.Models.UserDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDealers")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("LoanService")
                        .HasColumnType("bit")
                        .HasColumnName("Loan_Service");

                    b.Property<string>("MidleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("NocService")
                        .HasColumnType("bit")
                        .HasColumnName("NOC_Service");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Pincode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrimaryMobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("RegistrationService")
                        .HasColumnType("bit")
                        .HasColumnName("Registration_Service");

                    b.Property<string>("SecondaryMobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("UserDetail", (string)null);
                });

            modelBuilder.Entity("DMF_Services.Models.UserOtp", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("ID");

                    b.ToTable("UserOtp", (string)null);
                });

            modelBuilder.Entity("DMF_Services.Models.CarImage", b =>
                {
                    b.HasOne("DMF_Services.Models.CarDetail", "CarDetail")
                        .WithOne("CarImage")
                        .HasForeignKey("DMF_Services.Models.CarImage", "CarDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarDetail");
                });

            modelBuilder.Entity("DMF_Services.Models.CarDetail", b =>
                {
                    b.Navigation("CarImage");
                });
#pragma warning restore 612, 618
        }
    }
}
